#!/usr/bin/env ruby
# frozen_string_literal: true

# Create a folder
#
# When creating a Google Drive folder, you create a file with a MIME type of
# 'application/vnd.google-apps.folder' and a name. You can also specify the
# folder's parent folder(s) and other metadata.

require 'drive_v3'
require 'json'

drive_service = DriveV3.drive_service

# If name is not specified as part of a create request, the file name is named
# 'Untitled'.
name = 'My New Folder'

# If parents not specified as part of a create request or is an empty array, the
# folder is placed directly in the user's My Drive folder
#
# parents = ['id1', 'id2']
parents = []

# The MIME type of the file. Drive will attempt to automatically detect an
# appropriate value from uploaded content if no value is provided. The value
# cannot be changed unless a new revision is uploaded.
#
# A folder MIME type is 'application/vnd.google-apps.folder'
#
mime_type = 'application/vnd.google-apps.folder'

# If fields is not specified, the following default fields are returned:
# id, name, kind, and mime_type. '*' can by used to return all fields.
# See https://developers.google.com/drive/api/v3/reference/files#resource
#
fields = '*'

file_metadata = { name:, parents:, mime_type: }

begin
  file = drive_service.create_file(file_metadata, fields:)
  puts JSON.pretty_generate(file.to_h)
rescue StandardError => e
  puts "An error occurred: #{e.message}"
end
