#!/usr/bin/env ruby
# frozen_string_literal: true

# Permanently delete a file without moving it to the trash
#
# Moving a file to the trash is done by updating the file's trashed attribute to
# true. The process involves using the update method on the file you wish to move
# to the trash.

require 'drive_v3'

drive_service = DriveV3.drive_service

file_id = ARGV[0] || ENV.fetch('FILE_ID', nil)
raise 'Missing file_id' unless file_id

begin
  print 'Delete file...'
  # Does not return anything
  drive_service.delete_file(file_id)
  puts 'Success'
rescue StandardError => e
  puts "An error occurred: #{e.message}"
end
