#!/usr/bin/env ruby
# frozen_string_literal: true

# `recover_trashed_file` shows how to recover a file from the trash.
#
# Moving a file to the trash is done by updating the file's trashed attribute to
# true. To recover a trashed file is done by updating the file's trashed attribute
# to false.

require 'drive_v3'

drive_service = DriveV3.drive_service

file_id = ARGV[0] || ENV.fetch('FILE_ID', nil)
raise 'Missing file_id' unless file_id

begin
  print 'Recovering trashed file...'
  file_object = { trashed: false }
  file = drive_service.update_file(file_id, file_object)
  puts "update_file result:\n#{file.to_h.pretty_inspect}"
rescue StandardError => e
  puts "An error occurred: #{e.message}"
end
